### ISSUE TITLE
Add join/leave messages

### ISSUE THREAD

**Issue by mattmess1221** [PonyvilleSquare/ServerBridge#1]
I'd like to know when someone is joining the other server.

**Comment by ShroomAgent27** [comment]
Added https://github.com/PonyvilleSquare/ServerBridge/commit/89c7a85c81c0711acec5c0641ef24a9850dcde4b

**Comment by mattmess1221** [comment]
You forgot leave messages.

**Comment by ShroomAgent27** [comment]
Will be added for 1.11

**Comment by ShroomAgent27** [comment]
https://github.com/PonyvilleSquare/ServerBridge/commit/6083a55292405e26723d17584f7c27f309aa041d
